# syntax=docker/dockerfile:1
FROM scratch AS cuda-minimal-build
COPY --from=caffe3/void-apt-cuda-target /target-cuda-minimal-build /

FROM scratch AS cuda-devel
COPY --from=caffe3/void-apt-cuda-target /target-cuda-devel /

FROM scratch AS cuda-nsight-compute
COPY --from=caffe3/void-apt-cuda-target /target-cuda-nsight-compute /
