---
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        - { flavor: full, arch: x86_64 }
        - { flavor: full, arch: x86_64-musl }
        - { flavor: thin, arch: x86_64 }
        - { flavor: thin, arch: x86_64-musl }
        - { flavor: thin-bb, arch: x86_64 }
        - { flavor: thin-bb, arch: x86_64-musl }
        - { flavor: mini, arch: x86_64 }
        - { flavor: mini, arch: x86_64-musl }
        - { flavor: mini-bb, arch: x86_64 }
        - { flavor: mini-bb, arch: x86_64-musl }
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCHR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: void-robot
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile.${{ matrix.config.flavor }}"
          build-args:
            - ARCH="${{ matrix.config.arch }}"
            - BOOTSTRAP_VERSION="c45f924"
          push: true
          tags:
            - "ghcr.io/void-linux/void-${{ matrix.config.flavor }}:latest-${{ matrix.config.arch }}"
            - "ghcr.io/void-linux/void-${{ matrix.config.flavor }}:${{ github.event.inputs.version }}-${{ matrix.config.arch }}"
